on: 
  push:
    branch:
      main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 45.132.157.16
        username: u198691148
        password: R3nat42104!
        server-dir: public_html/geleias-artesanais/

        # server: ${{ secrets.ftp_host }}
        # username: ${{ secrets.ftp_user }}
        # password: ${{ secrets.ftp_password }}
        # server-dir: public_html/workspace